import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/theme-provider";
import { Albert_Sans } from 'next/font/google'
import { ISiteContext } from "@/interfaces";
import { getSiteContext } from "@/lib/general-utils";

const inter = Inter({ 
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-inter'
});

const albert_sans = Albert_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-albert-sans'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const context: ISiteContext =  getSiteContext()

  return (
    <html lang={context.locale} suppressHydrationWarning className={`${inter.variable} ${albert_sans.variable}`}>
      <head>
        <link rel="icon" href="/icon.ico" sizes="any" />
      </head>
      <body >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
